#
# Module manifest for MongrelDB
#
# Generated by: VisorCraft LLC
#

@{

# Script module or binary module file associated with this manifest.
RootModule        = 'MongrelDB.psm1'

# Version number of this module.
ModuleVersion     = '0.64.4'

# Supported PSEditions.
CompatiblePSEditions = @('Core', 'Desktop')

# ID used to uniquely identify this module.
GUID             = 'e1c4b7a2-9d3f-4a8e-b6c1-5f2d8e7a9b03'

# Author of this module.
Author           = 'VisorCraft LLC'

# Company or vendor of this module.
CompanyName      = 'VisorCraft LLC'

# Copyright statement.
Copyright        = '(c) 2024-2026 VisorCraft LLC. MIT OR Apache-2.0.'

# Description of the functionality provided by this module.
Description      = 'Pure PowerShell HTTP client for MongrelDB. Talks JSON over the Kit transaction, query, and SQL endpoints of a running mongreldb-server daemon. No external dependencies beyond built-in cmdlets (Invoke-WebRequest, ConvertTo-Json).'

# Minimum version of the Windows PowerShell engine required by this module.
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module.
# PowerShellHostName = ''

# Minimum version of the .NET Framework required by this module.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module.
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module.
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module.
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module.
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module.
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess.
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards.
FunctionsToExport = @(
    'Connect-MongrelDB',
    'Disconnect-MongrelDB',
    'Get-MongrelDBHealth',
    'Get-MongrelDBHistoryRetention',
    'Get-MongrelDBEarliestRetainedEpoch',
    'Set-MongrelDBHistoryRetention',
    'Get-MongrelDBTable',
    'New-MongrelDBTable',
    'Remove-MongrelDBTable',
    'Get-MongrelDBCount',
    'Add-MongrelDBRow',
    'Set-MongrelDBRow',
    'Remove-MongrelDBRow',
    'Invoke-MongrelDBTransaction',
    'Invoke-MongrelDBQuery',
    'New-MongrelDBCondition',
    'Invoke-MongrelDBSql',
    'Get-MongrelDBSchema',
    'Get-MongrelDBSchemaFor',
    'ConvertFrom-MongrelDBCommitHlc',
    'ConvertFrom-MongrelDBQueryStatus',
    'Get-MongrelDBCommitHlc',
    'Get-MongrelDBSerializationState',
    'Invoke-MongrelDBRetrieveText',
    'Get-MongrelDBQueryStatus',
    'Stop-MongrelDBQuery'
)

# Cmdlets to export from this module.
CmdletsToExport = @()

# Variables to export from this module.
VariablesToExport = @()

# Aliases to export from this module.
AliasesToExport = @()

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module.
FileList = @('MongrelDB.psm1')

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('MongrelDB', 'Database', 'HTTP', 'Client', 'SQL')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/visorcraft/MongrelDB-PowerShell/blob/master/LICENSE-MIT'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/visorcraft/MongrelDB-PowerShell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module.
        ReleaseNotes = 'Initial release of the MongrelDB PowerShell client.'

        # Prerelease string of this module.
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance.
        RequireLicenseAcceptance = $false

    }

}

# HelpInfo URI of this module.
# HelpInfoURI = ''

# Default prefix for commands exported from this module.
# DefaultCommandPrefix = ''

}
